sudo: true
dist: trusty 
os: linux
language: cpp 
compiler: g++ 
install: export CXX="g++-5" 
addons: 
    apt: 
    sources: 
    - ubuntu-toolchain-r-test 
    packages: 
    - g++-5 
notifications: 
email: 
    on_success: never 
    on_failure: never
before_install: sudo apt-get update -qq 
script: 
- cd test
- sudo bash ./test.sh
